### ISSUE TITLE
M5 Stack Core S3 - incorrect configuration of PSRAM chip - should be QUAD

### ISSUE THREAD

**Issue by georgik** [espressif/esp-brookesia#16]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

The application should start.

### Actual behavior (suspected bug)

The application is crashing during start, because PSRAM chip is different.
`sdkconfig` in the repo is configured with `OCTAL` which is in ESP32-S3-BOX-3, but M5Stack CoreS3 should be `QUAD`.

Please, update the sdkconfig, to
```
CONFIG_SPIRAM_MODE_QUAD=y
```

### Steps to reproduce the behavior

Flash and boot

### Project release version

master

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

macOS

### Shell

ZSH

**Comment by Lzw655** [comment]
Hi @georgik, thank you for pointing out this issue! It will be fixed soon.
